### ISSUE TITLE
Version 0.2.4 is significantly slower than 0.2.2

### ISSUE THREAD

**Issue by BrySchroeder** [NOhs/affine_transform_nd#22]
I've noticed that there is a significant slow-down in transform() from version 0.2.2 to version 0.2.4. For reference, using the function in the exact same way for both versions on a numpy array of size 650^3 takes about 0.1s for the former, while it takes a full 2s for the latter.

Any ideas for why this happens?

**Comment by NOhs** [comment]
Thanks for reporting this, will have a look at it.

**Comment by NOhs** [comment]
Should be fixed by #23. Version 0.2.5 will be out soon.
